### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wpbounce** [andrewchilds/jQuery.DomOutline#1]
Hi @andrewchilds
This is not an issue but more of a request.

Could you please provide a license file for jQuery.DomOutline or just add a link to the license in the source file?
I like the functionality and I would like to use it in the commercial project.

I'd appreciate any license that allows commercial use GPL, MIT or my favorite http://en.wikipedia.org/wiki/WTFPL :)

Thanks!
Igor

**Comment by andrewchilds** [comment]
MIT License added. Enjoy!
